olist:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-warehouse
      user: warehouse
      password: warehouse
      port: 5432
      dbname: warehouse
      schema: analytics
      threads: 4
